[build]
  publish = "frontend"
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python3 -m http.server 3000"
  port = 3000
  publish = "frontend" 